[project]
name = "openenv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.30.0",
    "openenv-core>=0.1.0",
    "transformers>=4.57.6",
]

[dependency-groups]
dev = [
    "openenv",
    "openenv-core>=0.1.0",
]

[tool.uv.sources]
openenv = { workspace = true }
